### ISSUE TITLE
Gobolinux Scripts should allow upgrade-path to git

### ISSUE THREAD

**Issue by shevegen** [gobolinux/Compile#1]
Hi,

I write this down on behalf of ThePub from the IRC channel.

He commented that the scripts were moved to git + github, which is fine, but there was no "scripts upgrade path" to get git repository support in the current system available. (I think he referred to 015 default install).

The git-move happened after the 015 installation .iso, so it is understandable that it offers no git-support, but perhaps that could be added? Some way that people can make use of git-update of components (in the event that bugs were fixed etc...)

In the past I think this happened when the Compile-Recipe was updated, perhaps this could now happen via git (no idea if anything else changed too).

The idea would be to have the Gobolinux Scripts work reliably.

Perhaps something like Compile --sync or something, or compile --git - no idea about the specific command.

**Comment by AitorATuin** [comment]
The easiest solution could be to create a Recipe using Compile/Scripts from git but i think that final users shouldn't use it. The proper way of working imho would be to release new versions from bugfixes and so on and let the users to use them providing a Package/Recipe for those versions.

Any other idea?

**Comment by hishamhm** [comment]
I _think_ `Compile Compile` works (or it has worked at some point), same with `Compile Scripts`. If these work with the versions of Compile+Scripts in 015, then yeah, packing new releases configured for Git should be the way to go. Users will need to be reminded to replace their Settings when upgrading, though.

**Comment by AitorATuin** [comment]
we have now recipes for `Scripts` and `Compile` so i think we can close this once both are reviewed and merge.

**Comment by hishamhm** [comment]
Great! I just approved the recipe in the Review Panel. (I confess haven't run those in my box, though)

**Comment by AitorATuin** [comment]
The Recipes were working what I'm not pretty sure about it's if the code in the master branch is working :)

**Comment by hishamhm** [comment]
Ah, I'm running the master branch :)
