### ISSUE TITLE
Compiling Ranger on GoboLinux 016.01 in a VM fails, says Scripts too old

### ISSUE THREAD

**Issue by mraper3** [gobolinux/Compile#24]
I've been trying to compile the Ranger recipe on GL 016.01 in a VirtualBox VM (Win 7 host), but it fails with these messages:

"/usr/bin/env: 'python': No such file or directory
Compile: Your Scripts package is too old. Please update it by running 'InstallPackage Scripts'."

I've confirmed that I have Python 2.7 installed using the 'which' command, and I've also confirmed that I have Scripts 016.01 installed by looking in the /Programs directory.  So I don't know why these errors are happening, but they are preventing the package from compiling.

Output from SystemInfo:
Kernel:           Linux 4.9.16-Gobo x86_64
Compilation: #0 SMP PREEMPT Mon Mar 20 08:53:55 BRT 2017
Processor:     Intel(R) Core(TM) i7-3940XM CPU @ 3.00 GHz
Memory:       16423312 kB

I'm not sure if this is the right place to bring this up, or if I should go to the recipe maker, or the Ranger devs themselves.  If you need more information, please let me know.  This is preventing me from installing the recipe, so any help you can give will be much appreciated.  Thanks!

**Comment by mraper3** [comment]
Oh right, the version of Ranger that Compile selected was 1.8.1-r1.

**Comment by AitorATuin** [comment]
Could you please open this issue in the Recipes repository? https://github.com/gobolinux/Recipes
Also the output from Compile would be useful.
Thanks.
