### ISSUE TITLE
Proposal: add --update or a similar tag to Compile (--update-scripts perhaps)

### ISSUE THREAD

**Issue by ghost** [gobolinux/Compile#25]
Hello lucas and hisham and everyone else,

I just had run Compile but python 3.x linked in. Compile complained but it also showed
the following:

Compile: Your Scripts package is too old. Please update it by running 'InstallPackage Scripts'.

My suggestion is:

(1) Perhaps Compile itself could also have a way to update (itself and/or also the Scripts collection)

I know from the ruby issue tracker that the ruby core team often wants explanations or even more importantly, a use case as to why, so here goes.

- I believe that this is just a convenience feature, nothing that important either way. Out of convenience, I think it may be useful if people could ALSO use e. g. "Compile --update-scripts" or "Compile --update-itself" or something like that. While it is admittedly not a real problem, since people can just use "InstallPackage Scripts" instead anyway, I thought it may be convenient. Of course you can also say that InstallPackage has to be used instead, which is perfectly fine too - making a distribution is about making choices and decisions. Thank you for reading, please feel free to close this issue at any moment in time.

**Comment by lucasvr** [comment]
Thanks for your feedback, and apologies for the late response.

We're going to ship Compile and Scripts as checked-out git trees for the coming 017 release. This way you will be able to update them by simply invoking `git pull`. The packages in 017_alpha already ships them like that, so I'm closing this issue for now.
