### ISSUE TITLE
Compile: fails if there is no temp dir to extract to existing

### ISSUE THREAD

**Issue by ghost** [gobolinux/Compile#28]
Compile Ruby
Compile: Locating a recipe for Ruby ...
Compile: Found recipe for Ruby 
GetRecipe: Trying to get http://gobolinux.org/recipe-store/Ruby--2.4.2-r1--recipe.tar.bz2
GetRecipe: Downloading recipe from http://gobolinux.org/recipe-store/Ruby--2.4.2-r1--recipe.tar.bz2
Compile: Recipe placed in /Data/Compile/Recipes/Ruby/2.4.2-r1
Compile: Checking dependencies...
Compile: Compiling Ruby version 2.4.2, revision r1.
--2018-01-11 21:34:42--  https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.gz
Resolving cache.ruby-lang.org... 2a04:4e42:1b::434, 151.101.113.178
Connecting to cache.ruby-lang.org|2a04:4e42:1b::434|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14187859 (14M) [application/octet-stream]
Saving to: 'ruby-2.4.2.tar.gz'

ruby-2.4.2.tar.gz                          100%[=======================================================================================>]  13.53M  7.38MB/s    in 1.8s    

2018-01-11 21:34:52 (7.38 MB/s) - 'ruby-2.4.2.tar.gz' saved [14187859/14187859]

Compile: Unpacking file /Data/Compile/Archives/ruby-2.4.2.tar.gz...

PrepareProgram: Preparing...
PrepareProgram: Autoconf configure script detected.

checking for ruby... /System/Index/bin/ruby
config.guess already exists
config.sub already exists
checking build system type... mkdir: cannot create directory '/Depot/Temp/cg9251-32697': No such file or directory
mkdir: cannot create directory '/Depot/Temp/cg-9251': No such file or directory
config.guess: cannot create a temporary directory in /Depot/Temp
configure: error: cannot guess build type; you must specify one
PrepareProgram: configure failed.
Compile: Ruby 2.4.2 - Configuration failed.

^^^ the above is on a fresh install on a laptop; sorry for the typos, typing on
this thing is AWFUL ...

Anyway, I usually use /Depot/Temp for temp files

in the case above, I forgot to create it

My suggestion to fix this: 

- Have Compile check whether a target directory exists, before
continuing. Right now it fails with "cannot guess build type;
you must specify one" but I believe this message is bogus
since the real error is that the directory does not exist yet.

**Comment by hishamhm** [comment]
Thanks for reporting! What's in your Compile.conf? (i.e. where did Compile get /Depot/Temp from?)

**Comment by Nuc1eoN** [comment]
No way to reproduce this and the original reporter is MIA.
Closing.
