### ISSUE TITLE
"make install" and Resources/Defaults/Settings

### ISSUE THREAD

**Issue by lucasvr** [gobolinux/Compile#36]
When one builds a recipe featuring a `Resources/Defaults/Settings` directory, Compile will place those files under `/Programs/Name/Version/Resources`, and SymlinkProgram will take care of copying them over to `/Programs/Name/Settings`.

When a recipe does not include `Resources/Defaults/Settings`, however, "make install" will overwrite settings files from previous versions of the same package at `/Programs/Name/Settings`. It looks like the most sensible thing to do is to:

1. Let 'make install' copy settings files to `/Programs/Name/Version/Resources/Defaults/Settings`
2. Overwrite files at `/P/N/V/Resources` with a recursive copy of the recipe's default settings, if that exists
3. Invoke UpdateSettings through SymlinkProgram (we already do this)

This approach, at the very least, prevents problems with lost or missing settings files after the compilation of a frequently updated package.

**Comment by hishamhm** [comment]
Makes sense :+1:
