### ISSUE TITLE
Compile not cloning Recipes repository (possible WiFi service incompatibility?)

### ISSUE THREAD

**Issue by munchkinhalfling** [gobolinux/Compile#42]
I am on a freshly-installed GoboLinux system, and I have never used GoboLinux before.

When I run, `sudo Compile LXDM`, it responds with this:
```
Password: 
Compile: Initializing recipes repository
Cloning into '/Data/Compile/Recipes'...
[...hangs for several minutes...]
fatal: unable to access 'https://github.com/gobolinux/Recipes.git/': getaddrinfo() thread failed to start

fatal: not a git repository (or any of the parent directories): .git
Compile: Could not find a recipe for LXDM
```
When I `sudo git clone` the Recipes repository by hand, it simply says `Cloning into 'Recipes'...` and hangs.
Even when I `git clone` as a regular user into my home directory, it hangs.
I have also tried `git clone` with a smaller repository, and that hangs as well.
I have found that when I `curl` anything, that hangs too.
Perhaps this is an incompatibility with the WiFi service?
Thank you in advance!

**Comment by munchkinhalfling** [comment]
I've solved it temporarily by downloading the ZIP from GitHub and unzipping it to /Data/Compile/Recipes, but it spits out errors about 'not a git repository' and such.

**Comment by lucasvr** [comment]
That's a known issue with this release. Please have a look at 
https://github.com/gobolinux/Documentation/wiki/GoboLinux-017-Known-Issues-and-Fixes and let us know if the `ifconfig` instructions fix it.

**Comment by munchkinhalfling** [comment]
Thanks! That's what was causing it.
