### ISSUE TITLE
Compile does not download all files specified under urls=()

### ISSUE THREAD

**Issue by Nuc1eoN** [gobolinux/Compile#52]
It seems that Compile, in the case of `Pahole 1.18`, does not download the second archive specified in the urls section.

To reproduce try `Compile Pahole 1.18`. It will fail with the message:
```
ls: cannot access '/Data/Compile/Archives/libbpf-0.2.tar.gz': No such file or directory
```
(If you are unable to reproduce, make sure  `libbpf-0.2.tar.gz` is not already present under `/Data/Compile/Archives/`)

Looking at the output, It appears that `Compile` does not even _attempt_ to download the archive.

**Comment by lucasvr** [comment]
Hi there. Yes, I just noticed what's going on. Will provide a fix in a couple of minutes.
