### ISSUE TITLE
What is the license for this?

### ISSUE THREAD

**Issue by 8bitprodigy** [gobolinux/Compile#56]
Would be good to know. Hopefully a permissive one for those of us who'd like to incorporate the GoboLinux approach to the filesystem under *BSD.

**Comment by lucasvr** [comment]
Hi there! Everything is licensed under the GPL version 2.

**Comment by 8bitprodigy** [comment]
Dang :(

**Comment by hishamhm** [comment]
There are no plans to change the licensing, but of course, this would not preclude using it alongside BSD-licensed software (gcc was the default compiler for FreeBSD for many years, after all). But in any case, be aware that Compile is not being actively maintained at this time. It would probably be a better idea to rewrite it in a better language than bash, and then you'd get to pick your favorite license. :)
