### ISSUE TITLE
startx not working after updating some programs 

### ISSUE THREAD

**Issue by garare992** [gobolinux/Compile#65]
![Screenshot_20240814_094724](https://github.com/user-attachments/assets/050256c9-a38b-4c28-b4db-ef72f50d6578)

**Comment by lucasvr** [comment]
It looks like Lua was updated to a new version, and AwesomeWM cannot find the old symbols anymore. Have a look at /Programs/Lua and update it as needed via `SymlinkProgram Lua <old_version>`

**Comment by garare992** [comment]
Thanks, that works.

**Comment by Nuc1eoN** [comment]
For reference, this is related to https://github.com/gobolinux/Recipes/issues/128
