### ISSUE TITLE
`configure` based recipes explicitly build static libs (even with --disable-static)

### ISSUE THREAD

**Issue by Nuc1eoN** [gobolinux/Compile#68]
Many `configure` (autotools) based recipes build static libs even if that is not the default behavior of the package (eg `libsm`), and even when when explicitly setting `--disable-static` (eg `LibXcomposite`).

I nailed it down to this commit: 
> Add $target as prefix for 'make install' variables
Define LIBTOOL, so that system wide (patched) libtool is used instead of autotool project's own shipped (unpatched) version

https://github.com/gobolinux/Compile/commit/8fc7b0dfe4cd934bcc4ca70b2a59036feef17709

Apparently we are running `make` as `make LIBTOOL=/usr/bin/libtool` in order to override the libtool version created by `configure` and use our ([patched](https://github.com/gobolinux/Recipes/tree/master/LibTool/2.5.3)) system version instead.

But the problem with that is that our system version of `libtool` will not get the `configure` treatment of the package. This essentially overrides flags we pass to configure like `--disable-static`, as this configuration will be specific to the generated `libtool` file residing inside build directory!

I am not an Autotools expert and I not sure which other settings could be affected. After all some packages have more fine grained options to control building static libs.

I would like to counsel how to solve this.

I have found a workaround to disable static libs generation **even when** using our system version by setting:
```bash
environment=(export LIBTOOLFLAGS="--tag=disable-static")
```
in our recipe. That configures our system `libtool` version correctly.

The other workaround is to comment out:
https://github.com/gobolinux/Compile/blob/531f48ee81f34f56408b154a4d62b5a59650dbf5/bin/Compile#L674-L678

The package appears to build fine. It seems it was not necessary to use the system version of `libtool` (at least in this case).

----

So what should we do to address this?
I can think of several options but none of them seem ideal:

- Ditch `make LIBTOOL=/usr/bin/libtool`. Use the system version only when absolutely necessary. But I do not know whether our patched `libtool` version is addressing a broader problem or if it is addressing just a corner case for select packages?
- Patch `libtool` dynamically in the build dir for configure based packages (probably unrealistic)
- Use `LIBTOOLFLAGS="--tag=disable-static"` by default, but then what if we want to actually build static libs? Should we set`LIBTOOLFLAGS="--tag=disable-static"` conditionally if we set `--disable-static` in the configure_options? Sounds too convoluted.
- Patch our system `libtool` so that it builds with static libs disabled by default. Still not ideal since again we are hardcoding stuff that probably shouldn't be...

IMO it is a problem that by using our system `libtool` we are overriding any defaults that would have been passed by configure. That makes our build system hard to understand as the behavior deviates how the packages would be build on other distros.

Note that this is not a problem for eg `Meson` based recipes as they do not use libtool.

@lucasvr I cannot think of a straight forward solution... Can I ask your thoughts on this?

**Comment by Nuc1eoN** [comment]
Since currently I am compiling many recipes, in the meantime I am using this kludge in `/Programs/Current/Functions/BuildType_configure`:
```diff
configure_do_build() {
+   if Array_Contains config "--disable-static"; then
+      export LIBTOOLFLAGS="--tag=disable-static"
+      Log_Debug "Recognized configure option --disable-static, setting LIBTOOLFLAGS=--tag=disable-static"
+   fi
   makefile_do_build
}
```

Maybe it is not so bad, as at least we do no need to run `autoreconf`.

The con is, that it is very specific to the `--disable-static` option.

**Comment by lucasvr** [comment]
Good catch!

Note that the use of a custom libtool was necessary because libtool fails to complete an installation if the build path differs from the install path. Patching the libtool file on the fly is something I considered a while ago, but it's complicated for two reasons. First, there are different variations of libtool scripts that make a regex-based approach a bit fragile. Second, some programs ship with or generate tenths of libtool files at configure time, which makes the implementation more challenging somewhat.

I think your workaround is good enough, as it won't affect other build systems and doesn't require updating dozens of existing recipes either.

**Comment by Nuc1eoN** [comment]
> Patching the libtool file on the fly is something I considered a while ago, but it's complicated for two reasons. First, there are different variations of libtool scripts that make a regex-based approach a bit fragile. Second, some programs ship with or generate tenths of libtool files at configure time, which makes the implementation more challenging somewhat.

Maybe it could work with multiple versions of libtool `patch` files, but that doesn't sound fun! :)

>I think your workaround is good enough, as it won't affect other build systems and doesn't require updating dozens of existing recipes either.

Cool!

Some corner cases could be if we specify `--enable-shared` or `--enable-static`... But it might still work since our libtool has shared & static linking enabled by default anyways.

Then there's `---disable-shared` but I can not find a single instance of this in our recipe base. So probably we just don't need it.

It will cover 98% of cases I guess, so I'll push it to the repo! :)

Thanks a lot Lucas!

-----

PS: Looks like ArchLinux has chosen to disable/strip static libs by default for their distro: https://archlinux.org/todo/remove-static-libraries/. If a program reqires them, a maintainer has to enable them explicitely via `options=('staticlibs')` in the PKGBUILD. 

And indeed - currently I see myself adding `--disable-static` to 99% of configure recipes :smile_cat:.

We might consider setting `export LIBTOOLFLAGS="--tag=disable-static"` as default, while providing an option like `build_static_links=yes` to enable static linking explicitly in the recipe.


Maybe that's not on the plate right now, but lets leave it here as a future note :)
